.PHONY: clean All

All:
	@echo "----------Building project:[ Geladeira - Debug ]----------"
	@cd "Geladeira" && "$(MAKE)" -f  "Geladeira.mk"
clean:
	@echo "----------Cleaning project:[ Geladeira - Debug ]----------"
	@cd "Geladeira" && "$(MAKE)" -f  "Geladeira.mk" clean
